### PR TITLE
Proposed implementation for daveaglick/Scripty#15

### PR DESCRIPTION
**Pull request by Herdo**
TODOs:
- use TotalIndention in Write methods of OutputFile
- might want to cache TotalIndention

### CODE REVIEW

**Comment by Herdo** [comment]
P.S.: I forgot the option to actually modify the `IndentionCharacter` and `IndentionRepeat`.
This could either happen via making the `OutputFile.Indention` property public, or via any kind of setup method.

**Comment by daveaglick** [comment]
Thanks :thumbsup: - I'll hopefully get a chance to look at this later today.

**Comment by daveaglick** [comment]
Related to #15

**Comment by daveaglick** [comment]
This looks like a good start. I still don't know how I feel about the namespace API proposed in #12, but I'm thinking that the indent API is general enough to make sense.

Some initial thoughts/questions:
- Would you be opposed to renaming `Indention` to `Indentation` which appears to be much more widely used?
- Instead of specifying an indent character and repeat, why not just specify an indent string? That way you can use the indentation logic for more exotic scenarios where the indentations aren't the same character.
- An overload of `IIndention.Indent()` that takes a string for the indentation string would be cool too - that way you could even do special indentations that are different from the preset one when required.
- Another overload that takes an `int` for adding multiple indents would also be neat, but we'd have to be sure to pop them all on dispose (since the indent string is stored in the stack in aggregate, I wouldn't think this part is an issue).
- What if I want to output something without indentation while in the middle of an indented block (for example, a `#region` while inside a class)? Is there a way to temporarily escape the indentation?

I think my biggest question with the proposal is how it will work for adding the indents before a line. `WriteLine()` adds the newline character(s) at the end of a line, so how will we know to indent the _next_ character? Will the indent be output after every `WriteLine()` call, even if I don't output anything else? That doesn't work if I change the indent level after writing. What about when I don't use `WriteLine()` for everything or if I output a newline manually? To consider all of this, what would the output be for this sequence of calls:

```
Output.Indentation.Content = "...";
Output.WriteLine("A");
using(Output.Indent())
{
  Output.WriteLine("B");
  Output.Write('C');
  using(Output.Indent())
  {
    Output.Write('D');
    Output.Write("\r\n");
    Output.Write("E");
    Output.WriteLine("F");
  }
  Output.Write("G");
  Output.WriteLine("H");
}
Output.Write("I");
```

At first glance I would think this results in (though this may be open for discussion, especially regarding C and D:

```
A
...B
...CD
......EF
...GH
I
```

**Comment by TylerBrinkley** [comment]
I don't think the Indentation feature should consider NewLine characters within the values it writes as it may have unintended consequences such as when writing a verbatim string literal and would be much harder to implement. I think it should only take effect when the user uses the WriteLine methods, thus the behavior for C & D as you have it would be correct.

**Comment by Herdo** [comment]
- `Indentation` is fine with me
- The `Content` property should be called `Default` - however, setting a complete string is fine, too
- The overload with the `int` is obsolete in my opinion - what would be the benefit of writing `Indent(2)` over `Indent("......")` (using 3 dots as `Default`)

### Looking ahead about writing without indention:

Taking #27 into account, probably a set of `WriteRaw` and `WriteLineRaw` methods could be an option - ignoring all "extensions".

I agree with @Tydude4Christ about the new lines.
`Write` and `WriteLine` won't indent, except the previous statement was a `WriteLine`.
Remember that you could call WriteLine, Write, Write, WriteLine.
The last 3 will build a complete line. So `WriteLine` won't always write with indention.

**Comment by TylerBrinkley** [comment]
I took my stab at it with this pull request #28.

**Comment by daveaglick** [comment]
@Herdo 
- Agree with `Default` for property name
- Also agree the `Indent(int)` overload is probably overkill

> `Write` and `WriteLine` won't indent, except the previous statement was a `WriteLine`

I think this is the exact right way to go. _Both_ `Write` and `WriteLine` should indent, but _only_ if the previous call was to `WriteLine`. I suspect that means there will need to be a flag `_indentNextWrite` (or something) that gets set on a call to `WriteLine` and then checked on every write, but any other way to implement that behavior would be fine too.

As for "escaping" the indent, let's come back to that once the rest is implemented. I've got some thoughts on #27 that I'll post there, but in short I'm not a big fan of introducing an alternate `WriteRaw` set of methods.

Thanks for all the help working through some of these proposals!

**Comment by daveaglick** [comment]
This was (kind of) merged in. Indentation support _is_ coming, but I ended up going a slightly different way than either this or the other PR (hopefully you'll agree it's a nice API).

In short, you can now write this:

```
Output.IndentString = "...";
Output.WriteLine("A");
using(Output.WithIndent())
{
  Output.WriteLine("B");
  Output.Write('C');

  // Indents a block of text without needing a disposable
  Output.Indent()
  Output.Write('D');
  Output.Write("\r\n");
  Output.Write("E");
  Output.WriteLine("F");
  Output.IndentLevel--;

  // "Resets" the indent temporarily
  using(Output.WithIndent(0))
  {
    Output.Write("G");
    Output.WriteLine("H");
  }
}
Output.Write("I");
```

**Pull request merged**
