### PR TITLE
Cake addin

### LINKED ISSUE #7: Create Cake addin

### PR DESCRIPTION
**Pull request by agc93**
Resolves #7 .

This is just a quick knock-up of a `Tool<T>`-based addin, wrapping the scripty.exe tool.

Let me know if you have any feedback, happy to discuss approach and changes etc

### CODE REVIEW

**Comment by agc93** [comment]
Also the tests are a bit sketchy as I'm not very familiar with NUnit

**Comment by daveaglick** [comment]
This is great, thanks! :thumbsup: I'll hopefully get a chance to look at it after the long weekend (it's a holiday in the US on Monday).

**Comment by daveaglick** [comment]
This was awesome, thanks a bunch. The package for the new Cake addin will get published on the next release (not sure when that'll be).

**Comment by daveaglick** [comment]
No worries about the tests - I'll clean them up a little.

**Pull request merged**
