### PR TITLE
Cake Retarget

### LINKED ISSUE #94: Cake Addin Built With Wrong .NET Version
The Cake addin is using the wrong version of .NET. Cake currently only supports 4.5 and .NET Standard 1.6 (https://github.com/cake-build/cake/issues/1015)

The current Cake addin is built on 4.5.2 which means Cake cannot load it and you get an error saying "Could not find any assemblies compatible with .NETFramework,Version=v4.5". This may have been caused by this bug https://github.com/cake-build/cake-vs/issues/61 which means that the VS Extension creates addins on that version despite them not working with Cake.

I think the fix is just to downgrade the addin to 4.5. However the rest of the project targets 4.6 so I'm not really sure if that is viable. You could retarget to netstandard 1.6 which is sort of equivalent to 4.6.1, but that is not exactly trivial either.

Has anyone actually tested and run the Cake addin, because I am not sure how it could have ever worked or am I missing something?

### PR DESCRIPTION
**Pull request by crash-dive**
I have change the Cake.Scripty to 4.5. I also updated the README, added syntax highlighting to the code blocks and fixed another issue which tripped me up earlier where the README still referred to the item group "ScriptFile" not "ScriptyFile".

Fixed #94

### CODE REVIEW

**Comment by crash-dive** [comment]
I have just tried to use this and I have realised a couple of other flaws in the original design. The settings are not really settings because well you cannot set them, they are just set to a private property and then passed to the underlying Run method.

I am just going to fix that and update the pull request.

**Comment by crash-dive** [comment]
You can now set the settings. I have kept the API surface compatible with the old one so no breaking changes.

**Comment by daveaglick** [comment]
Awesome, thanks! I'll get this merged and released first thing tomorrow.

**Comment by daveaglick** [comment]
Thanks again! So "first thing" got overtaken by the day job, but going to try to get a release out sometime today if I can square away a few other things.

**Review by nnxshop — APPROVED** [review]

**Pull request merged**
