### PR TITLE
Output behavior

### PR DESCRIPTION
**Pull request by StingyJack**
Let me know if anything needs adjustment, squashing and branching was a nightmare.  I would _almost_ take Visual Source Save 6.0a over Git + Vim.

### CODE REVIEW

**Comment by daveaglick** [comment]
It looks like this probably needs to be rebased after the previous PRs were merged. Once you rebase the branch locally and then push it to GitHub (you may need to force rewriting the HEAD in your GitHub branch) it should update the PR and hopefully the conflicts will go away.

Just a note about your previous PR - I removed the Docs and Build projects from the solution file. I generally prefer to keep non-code artifacts out of the Visual Studio solution.

Thanks!

**Comment by StingyJack** [comment]
The docs and build were solution folders so i didnt have to go navigating to the filesystem. I've used an emptied out web site project for that kind of thing before, but they were just conveniences. 

I'll see what I can figure out about straightening the HEAD.  

I put a few loose ideas on my fork's issue list if you want to take a look and comment. Thanks for your patience.

**Comment by daveaglick** [comment]
I'm finally getting a chance to read through this. Thank again for the contribution. Don't worry too much about further git cleanup - I can do some cleanup after merging if needed.

I'd like to understand exactly what we're trying to accomplish here. Is there an associated issue? I couldn't find one, and that's okay, I just want to make sure this PR is tied to the issue if there is one.

It looks like this change is intended to write output to a temporary file and then moves (?) the temporary file to the correct output file location when evaluation is complete if no errors have occurred. Additionally there are options to control whether to actually write the output or not. Do I have that about right?

If so, some questions come to mind:
- What is the underlying problem this change resolves? Were you running into issues with valid output being overwritten with invalid content when the script crashed?
- Is there a reason why temporary files are used instead of just buffering the output in memory and then flushing it to disk (or not)?
- What is the use case for the setting when no output is written (`Output.KeepOutput = false`)? Since the output streams are only created/opened when calls to write methods are used, if using Scripty only as tooling without any intent to write output wouldn't create files anyway.

Thanks - this is a big change that all the other users would need to understand, so I need to understand it well myself first.

**Comment by StingyJack** [comment]
(I tried to reply on my phone and it decided that the spelling correction i picked meant half edit, then close and reopen the PR)

#63 outlines the impetus, and #69 has other corrections noted below. 

Scripty suffers the same problem as T4 when used for generating code - always overwrites any output so long as it can compile. With these ISVSingleFileGenerator I find that visual studio saves the file _all the frigging time_. I had looked into creating a custom T4 host a while back and it seemed overly difficult, and it seemed far less difficult to add a configurable behavior to scripty.

The output behavior will default to current model, but there are two other possibilities.
- Never generate output (what it says) 
- Script Controls Output - letting the script selectively determine which outputs it wants to keep...

```
Output["debug.log"].KeepOutput = errorOccured;
Output["CodeFile.cs"].KeepOutput = true;

//or just this if you only used the default outputter
Output.KeepOutput = false;
```
There's a Tools -> Options -> ScriptyOptions page in VS to govern this globally and where more settings can be added.

There were some other unclear bits around the naming between the default output and additional output, and some odd interplay when set file path/extension were used with multiple outputs (this may assist @dstrohschein the followup for #70)

This makes for other usages of scripty outside of codegen or build time activity. (https://github.com/StingyJack/Scripty/issues has some of these half baked concoctions)

The temp files vs memory was because I have no idea how large of an output some are generating. There was at least one person who wanted raw bytes to make files. Temp files seemed safer (disk space often more available) and if anything catastrophic happened they could be available for forensics.

The first PR was pushed back along with some other changes and I couldn't get git to just "merge and move on" (and found a small miss from the pushed changes). I tried a few things and ended up with the cleanest history I could muster before cursing Linus.

**Comment by StingyJack** [comment]
Yay mobile web version and autocorrect

Xompi = compile.

... The output behaviors default to current model, but allow for two other possibilities. Never generate output (what it says) or letting the script selectively determine which outputs it wants to keep.

And a confg page in vs options.

**Comment by StingyJack** [comment]
I think i figured out how to fix my branch history, I'll resubmit and add these comments.

**Pull request closed without merging**
