### PR TITLE
Potential Indentation Support Implementation

### PR DESCRIPTION
**Pull request by TylerBrinkley**
Here's my stab at #15.

### CODE REVIEW

**Comment by TylerBrinkley** [comment]
@daveaglick, when you get the chance could you look at this PR? Thanks.

**Comment by daveaglick** [comment]
@Tydude4Christ I probably won't have a chance until next week. What little OSS time I have available today I'm hoping to use getting a new Scripty release out there.

**Comment by TylerBrinkley** [comment]
No problem. Thanks.

**Comment by daveaglick** [comment]
@TylerBrinkley Thanks a lot for this :thumbsup:. I'd like to (finally) get this feature closed out so that I can move on to other issues. In general, I like the API in #21 just a bit more so I'm going to go ahead and pull that one in. It also needs a little rework though, so I'll probably reuse some of the concepts here (such as returning an special object to track the indentation request).

If you have any additional suggestions for the final API once I finish tweaking it and get it checked in, I'd certainly welcome further pull requests.

**Pull request closed without merging**
