### PR TITLE
Adding debugging - getting started

### PR DESCRIPTION
**Pull request by StingyJack**
#64 - partly, anyway. Modify or edit as you see fit.

### CODE REVIEW

**Comment by daveaglick** [comment]
This is totally awesome, thanks! I'm going to try really hard to carve some time next week to look at it (and put together a release with what you've got so far). Is this PR ready to merge or is it a work in progress?

**Comment by StingyJack** [comment]
The second two shouldn't really be in that PR, I'm not entirely clear on the mechanics of github. I only meant to send the debugging markdown for now. Any idea how I can stack up commits so they come in through PR? 

I wanted to add command switch to scripty.exe for the on save behavior, some docs, and a few unit tests to make sure its covered well enough (and that I didn't break anything). Also had an idea about using menu commands instead of relying on Run Custom Tool - Run with Scripty and Debug with Scripty would make a bit easier to use (provided debugging can be figured out) but that can be later.

**Comment by daveaglick** [comment]
The trick for multiple simultaneous PRs is to originate them from different branches. If you move those other commits to a different branch you can open a new PR that includes them. Then just force-push this branch without the other commits and it'll update the PR to only contain the first one.

**Comment by StingyJack** [comment]
Gimmie a day or so to sort it out, I cant seem to get a safe feeling from the recommendations I'm finding on how to "move" them (delete the deltas in a delta based vcs) and its been a particularly hard week.

**Comment by daveaglick** [comment]
No rush. As you may have been able to tell, my attention recently has been focused on another of my OSS projects. One of these days I'll get back to Scripty and clear the backlog, but today is not that day.

**Comment by StingyJack** [comment]
This should be the single commit now.

**Comment by daveaglick** [comment]
Thanks! :+1:

**Pull request merged**
